#ifndef _MYWATCH_ESP32_S3_SMARTWATCH_CONFIG_H_
#define _MYWATCH_ESP32_S3_SMARTWATCH_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
// ES7210 provides microphone ADC channels on this board; it does not expose
// a DAC playback reference channel for the AFE. Treat input as microphone-only
// so device AEC cannot use a second microphone as a false echo reference.
#define AUDIO_INPUT_REFERENCE false

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_16
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_41
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_42
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_40

#define AUDIO_CODEC_PA_PIN GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_15
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_14
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR ES7210_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define DISPLAY_QSPI_CS_PIN GPIO_NUM_12
#define DISPLAY_QSPI_PCLK_PIN GPIO_NUM_11
#define DISPLAY_QSPI_DATA0_PIN GPIO_NUM_4
#define DISPLAY_QSPI_DATA1_PIN GPIO_NUM_5
#define DISPLAY_QSPI_DATA2_PIN GPIO_NUM_6
#define DISPLAY_QSPI_DATA3_PIN GPIO_NUM_7
#define DISPLAY_RESET_PIN GPIO_NUM_8
#define DISPLAY_WIDTH 410
#define DISPLAY_HEIGHT 502
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define TOUCH_RESET_PIN GPIO_NUM_9
#define TOUCH_INTERRUPT_PIN GPIO_NUM_38

#define IMU_I2C_ADDRESS 0x6B
#define RTC_I2C_ADDRESS 0x51
#define IMU_INTERRUPT_PIN GPIO_NUM_21

#endif  // _MYWATCH_ESP32_S3_SMARTWATCH_CONFIG_H_
